on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
      - run: >
          mongo_url="${{secrets.mongo_url}}"
          mongo_database="${{secrets.mongo_database}}"
          build/build.bash
      - uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{secrets.neocities_token}}
          cleanup: true
