on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: >
          neocities_auth="${{secrets.neocities_auth}}"
          mongo_url="${{secrets.mongo_url}}"
          mongo_database="${{secrets.mongo_database}}"
          build/build.bash
